run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - go-backup

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 150
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 150
  goimports:
    local-prefixes: github.com/p5yheimu/dify-plugin-sso
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - unnamedResult
      - hugeParam

linters:
  enable:
    - bodyclose
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - misspell
    - unconvert
    - whitespace
    - nolintlint

  disable:
    - deadcode
    - structcheck
    - varcheck
    - maligned
    - scopelint
    - golint
    - interfacer
    - depguard
    - dogsled
    - dupl
    - funlen
    - gochecknoinits
    - gocyclo
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - lll
    - nakedret
    - noctx
    - rowserrcheck
    - stylecheck
    - unparam
    - gocritic

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - goconst
        - gocyclo
        - dupl
    
    - path: cmd/
      linters:
        - gomnd
        - funlen
        
    - path: internal/auth/saml/
      text: "weak cryptographic primitive"
      linters:
        - gosec
        
    - text: "G404: Use of weak random number generator"
      linters:
        - gosec

    - text: "shadow: declaration of"
      linters:
        - govet

  exclude-use-default: false
  exclude:
    - 'declaration of "(err|ctx)" shadows declaration at'
    - 'G104: Errors unhandled'
    - 'G204: Subprocess launched with variable'
    - 'G301: Poor file permissions used when creating a directory'
    - 'G302: Poor file permissions used when creating a file'
    - 'G304: Potential file inclusion via variable'
    - 'exported .* should have comment'
    - 'comment on exported .* should be of the form'
    - 'should not use dot imports'
    - 'cyclomatic complexity .* of func .* is high'

severity:
  default-severity: error
  case-sensitive: false 